-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 09:28:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prova04
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prova04` ;

-- -----------------------------------------------------
-- Schema prova04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prova04` DEFAULT CHARACTER SET utf8 ;
USE `prova04` ;

-- -----------------------------------------------------
-- Table `prova04`.`tipo_assinante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`tipo_assinante` ;

CREATE TABLE IF NOT EXISTS `prova04`.`tipo_assinante` (
  `cd_tipo` INT AUTO_INCREMENT NOT NULL,
  `ds_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`cd_tipo`))
ENGINE = InnoDB;

INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('tipoA');
INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('tipoB');
INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('tipoC');
INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('tipoD');
INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('residencial');
INSERT INTO `prova04`.`tipo_assinante` (`ds_tipo`) VALUES ('comercial');
SELECT * FROM `prova04`.`tipo_assinante`;

-- -----------------------------------------------------
-- Table `prova04`.`ramo_atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`ramo_atividade` ;

CREATE TABLE IF NOT EXISTS `prova04`.`ramo_atividade` (
  `cd_ramo` INT AUTO_INCREMENT NOT NULL,
  `ds_ramo` VARCHAR(45) NULL,
  PRIMARY KEY (`cd_ramo`))
ENGINE = InnoDB;

INSERT INTO `prova04`.`ramo_atividade` (`ds_ramo`) VALUES ('ramoA');
INSERT INTO `prova04`.`ramo_atividade` (`ds_ramo`) VALUES ('ramoB');
INSERT INTO `prova04`.`ramo_atividade` (`ds_ramo`) VALUES ('ramoC');
INSERT INTO `prova04`.`ramo_atividade` (`ds_ramo`) VALUES ('ramoD');
SELECT * FROM `prova04`.`ramo_atividade`;



-- -----------------------------------------------------
-- Table `prova04`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`telefone` ;

CREATE TABLE IF NOT EXISTS `prova04`.`telefone` (
  `cd_fone` INT AUTO_INCREMENT NOT NULL,
  `ddd` VARCHAR(45) NULL,
  `n_fone` VARCHAR(45) NULL,
  PRIMARY KEY (`cd_fone`))
ENGINE = InnoDB;

INSERT INTO `prova04`.`telefone` (`ddd`, `n_fone`) VALUES ('DDDA', 'numeroA');
INSERT INTO `prova04`.`telefone` (`ddd`, `n_fone`) VALUES ('DDDB', 'numeroB');
INSERT INTO `prova04`.`telefone` (`ddd`, `n_fone`) VALUES ('DDDC', 'numeroC');
INSERT INTO `prova04`.`telefone` (`ddd`, `n_fone`) VALUES ('DDDD', 'numeroD');
INSERT INTO `prova04`.`telefone` (`ddd`, `n_fone`) VALUES ('DDDD', 'numeroE');
SELECT * FROM `prova04`.`telefone`;


-- -----------------------------------------------------
-- Table `prova04`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`municipio` ;

CREATE TABLE IF NOT EXISTS `prova04`.`municipio` (
  `cd_municipio` INT AUTO_INCREMENT NOT NULL,
  `ds_municipio` VARCHAR(45) NULL,
  PRIMARY KEY (`cd_municipio`))
ENGINE = InnoDB;

INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('municipioA');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('municipioB');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('municipioC');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('municipioD');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('Pelotas');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('Natal');
INSERT INTO `prova04`.`municipio` (`ds_municipio`) VALUES ('João Câmara');

SELECT * FROM `prova04`.`municipio`;


-- -----------------------------------------------------
-- Table `prova04`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`endereco` ;

CREATE TABLE IF NOT EXISTS `prova04`.`endereco` (
  `cd_endereco` INT AUTO_INCREMENT NOT NULL,
  `ds_endereco` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `telefone_cd_fone` INT NOT NULL,
  `municipio_cd_municipio` INT NOT NULL,
  PRIMARY KEY (`cd_endereco`),
  INDEX `fk_endereco_telefone_idx` (`telefone_cd_fone` ASC) VISIBLE,
  INDEX `fk_endereco_municipio1_idx` (`municipio_cd_municipio` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_telefone`
    FOREIGN KEY (`telefone_cd_fone`)
    REFERENCES `prova04`.`telefone` (`cd_fone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_municipio1`
    FOREIGN KEY (`municipio_cd_municipio`)
    REFERENCES `prova04`.`municipio` (`cd_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `prova04`.`endereco` (`ds_endereco`, `complemento`, `bairro`, `cep`, `telefone_cd_fone`, `municipio_cd_municipio`) VALUES ('enderecoA', 'complementoA', 'bairroA', 'cepA', 1, 5);
INSERT INTO `prova04`.`endereco` (`ds_endereco`, `complemento`, `bairro`, `cep`, `telefone_cd_fone`, `municipio_cd_municipio`) VALUES ('enderecoB', 'complementoB', 'bairroB', 'cepB', 2, 6);
INSERT INTO `prova04`.`endereco` (`ds_endereco`, `complemento`, `bairro`, `cep`, `telefone_cd_fone`, `municipio_cd_municipio`) VALUES ('enderecoC', 'complementoC', 'bairroC', 'cepC', 3, 7);
INSERT INTO `prova04`.`endereco` (`ds_endereco`, `complemento`, `bairro`, `cep`, `telefone_cd_fone`, `municipio_cd_municipio`) VALUES ('enderecoD', 'complementoD', 'bairroD', 'cepD', 4, 5);
INSERT INTO `prova04`.`endereco` (`ds_endereco`, `complemento`, `bairro`, `cep`, `telefone_cd_fone`, `municipio_cd_municipio`) VALUES ('enderecoA', 'complementoA', 'bairroA', 'cepA', 5, 5);
SELECT * FROM `prova04`.`endereco`;


-- -----------------------------------------------------
-- Table `prova04`.`assinante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prova04`.`assinante` ;

CREATE TABLE IF NOT EXISTS `prova04`.`assinante` (
  `cd_assinante` INT AUTO_INCREMENT NOT NULL,
  `nm_assinante` VARCHAR(45) NULL,
  `tipo_assinante_cd_tipo` INT NOT NULL,
  `ramo_atividade_cd_ramo` INT NOT NULL,
  `endereco_cd_endereco` INT NOT NULL,
  PRIMARY KEY (`cd_assinante`),
  INDEX `fk_assinante_tipo_assinante1_idx` (`tipo_assinante_cd_tipo` ASC) VISIBLE,
  INDEX `fk_assinante_ramo_atividade1_idx` (`ramo_atividade_cd_ramo` ASC) VISIBLE,
  INDEX `fk_assinante_endereco1_idx` (`endereco_cd_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_assinante_tipo_assinante1`
    FOREIGN KEY (`tipo_assinante_cd_tipo`)
    REFERENCES `mydb`.`tipo_assinante` (`cd_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assinante_ramo_atividade1`
    FOREIGN KEY (`ramo_atividade_cd_ramo`)
    REFERENCES `mydb`.`ramo_atividade` (`cd_ramo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assinante_endereco1`
    FOREIGN KEY (`endereco_cd_endereco`)
    REFERENCES `mydb`.`endereco` (`cd_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `prova04`.`assinante` (`nm_assinante`, `tipo_assinante_cd_tipo`, `ramo_atividade_cd_ramo`, `endereco_cd_endereco`) VALUES ('AssinanteNumeroA', 1, 1, 1);
INSERT INTO `prova04`.`assinante` (`nm_assinante`, `tipo_assinante_cd_tipo`, `ramo_atividade_cd_ramo`, `endereco_cd_endereco`) VALUES ('AssinanteNumeroB', 2, 2, 2);
INSERT INTO `prova04`.`assinante` (`nm_assinante`, `tipo_assinante_cd_tipo`, `ramo_atividade_cd_ramo`, `endereco_cd_endereco`) VALUES ('AssinanteNumeroC', 3, 3, 3);
INSERT INTO `prova04`.`assinante` (`nm_assinante`, `tipo_assinante_cd_tipo`, `ramo_atividade_cd_ramo`, `endereco_cd_endereco`) VALUES ('AssinanteNumeroD', 4, 4, 4);
INSERT INTO `prova04`.`assinante` (`nm_assinante`, `tipo_assinante_cd_tipo`, `ramo_atividade_cd_ramo`, `endereco_cd_endereco`) VALUES ('AssinanteNumeroA', 5, 1, 5);

SELECT * FROM `prova04`.`assinante`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- inner join 
-- left join
-- right join
-- full join

-- letra A

SELECT *
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`telefone`
ON `prova04`.`endereco`.`telefone_cd_fone` = `prova04`.`telefone`.`cd_fone`;

-- letra B

SELECT `prova04`.`assinante`.`nm_assinante`, `prova04`.`ramo_atividade`.`ds_ramo`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`ramo_atividade` 
ON `prova04`.`assinante`.`ramo_atividade_cd_ramo` = `prova04`.`ramo_atividade`.`cd_ramo`;

SELECT `prova04`.`assinante`.`nm_assinante`, `prova04`.`ramo_atividade`.`ds_ramo`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`ramo_atividade` 
ON `prova04`.`assinante`.`ramo_atividade_cd_ramo` = `prova04`.`ramo_atividade`.`cd_ramo`
ORDER BY `prova04`.`ramo_atividade`.`ds_ramo` DESC;

SELECT `prova04`.`assinante`.`nm_assinante`, `prova04`.`ramo_atividade`.`ds_ramo`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`ramo_atividade` 
ON `prova04`.`assinante`.`ramo_atividade_cd_ramo` = `prova04`.`ramo_atividade`.`cd_ramo`
ORDER BY `prova04`.`assinante`.`nm_assinante` DESC;

-- letra C

SELECT *
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`municipio` 
ON `prova04`.`endereco`.`municipio_cd_municipio` = `prova04`.`municipio`.`cd_municipio`
INNER JOIN `prova04`.`tipo_assinante`
ON `prova04`.`assinante`.`tipo_assinante_cd_tipo` = `prova04`.`tipo_assinante`.`cd_tipo`
WHERE `prova04`.`municipio`.`ds_municipio` = 'Pelotas' AND `prova04`.`tipo_assinante`.`ds_tipo` = 'residencial';

SELECT `prova04`.`assinante`.`nm_assinante`, `prova04`.`municipio`.`ds_municipio`, `prova04`.`telefone`.`n_fone`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`municipio` 
ON `prova04`.`endereco`.`municipio_cd_municipio` = `prova04`.`municipio`.`cd_municipio`
INNER JOIN `prova04`.`tipo_assinante`
ON `prova04`.`assinante`.`tipo_assinante_cd_tipo` = `prova04`.`tipo_assinante`.`cd_tipo`
WHERE `prova04`.`municipio`.`ds_municipio` = 'Pelotas' AND `prova04`.`tipo_assinante`.`ds_tipo` = 'residencial';


-- letra D

SELECT *
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`telefone` 
ON `prova04`.`endereco`.`telefone_cd_fone` = `prova04`.`telefone`.`cd_fone`
HAVING SUM(`prova04`.`endereco`.`telefone_cd_fone`)>1;

SELECT `prova04`.`assinante`.`nm_assinante`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`telefone` 
ON `prova04`.`endereco`.`telefone_cd_fone` = `prova04`.`telefone`.`cd_fone`
HAVING SUM(`prova04`.`endereco`.`telefone_cd_fone`)>1;

-- letra E

SELECT `prova04`.`assinante`.`nm_assinante`, `prova04`.`telefone`.`n_fone`, `prova04`.`tipo_assinante`.`ds_tipo`, `prova04`.`municipio`.`ds_municipio`
FROM `prova04`.`assinante`
INNER JOIN `prova04`.`endereco` 
ON `prova04`.`assinante`.`endereco_cd_endereco` = `prova04`.`endereco`.`cd_endereco`
INNER JOIN `prova04`.`telefone` 
ON `prova04`.`endereco`.`telefone_cd_fone` = `prova04`.`telefone`.`cd_fone`
INNER JOIN `prova04`.`municipio` 
ON `prova04`.`endereco`.`municipio_cd_municipio` = `prova04`.`municipio`.`cd_municipio`
INNER JOIN `prova04`.`tipo_assinante`
ON `prova04`.`assinante`.`tipo_assinante_cd_tipo` = `prova04`.`tipo_assinante`.`cd_tipo`
WHERE `prova04`.`municipio`.`ds_municipio` = 'Natal' OR `prova04`.`municipio`.`ds_municipio` = 'João Câmara';
